export interface JestError {
  type: string;
  message: string;
  suggestedFixes: string[];
  details?: any;
}

export interface JestErrorAnalysis {
  hasErrors: boolean;
  errors: JestError[];
  suggestedFixes: string[];
}

/**
 * Analyze Jest STDERR and STDOUT to identify common error patterns
 * and provide actionable suggested fixes
 */
export function analyzeJestErrors(stderr: string, stdout: string): JestErrorAnalysis {
  const errors: JestError[] = [];

  // Pattern 1: Cannot find module
  if (stderr.includes('Cannot find module') || stdout.includes('Cannot find module')) {
    const moduleMatches = (stderr + stdout).match(/Cannot find module '([^']+)'/g);
    const modules = moduleMatches ? Array.from(new Set(moduleMatches)) : [];

    errors.push({
      type: 'MODULE_NOT_FOUND',
      message: `Tests import modules that do not exist (${modules.length} modules)`,
      details: { modules },
      suggestedFixes: [
        'The test file imports modules that haven\'t been created yet',
        'System will auto-create scaffolds for local imports',
        'If it\'s an npm package, add it to package.json and run npm install'
      ]
    });
  }

  // Pattern 2: Syntax errors in test file
  if (stderr.includes('SyntaxError') || stdout.includes('SyntaxError')) {
    const syntaxMatch = (stderr + stdout).match(/SyntaxError: (.+)/);
    errors.push({
      type: 'SYNTAX_ERROR',
      message: syntaxMatch ? syntaxMatch[1] : 'Test file has syntax errors',
      suggestedFixes: [
        'Check test file for syntax errors (missing brackets, semicolons, etc.)',
        'Run TypeScript compiler to verify: npx tsc --noEmit',
        'Review the test file code generated by AI'
      ]
    });
  }

  // Pattern 3: No tests found (0 total)
  if (stdout.includes('0 total') || (!stdout.includes('Tests:') && stdout.includes('Ran all'))) {
    errors.push({
      type: 'NO_TESTS_FOUND',
      message: 'Jest found 0 tests to execute',
      suggestedFixes: [
        'Verify test file has describe() and it() blocks',
        'Check jest.config matches test file location',
        'Ensure test file extension is .test.ts or .spec.ts',
        'File may have syntax errors preventing Jest from loading it'
      ]
    });
  }

  // Pattern 4: TypeScript compilation errors
  if (stderr.includes('TS') && stderr.match(/TS\d+:/)) {
    const tsErrors = (stderr.match(/TS\d+:.+/g) || []).slice(0, 3);
    errors.push({
      type: 'TYPESCRIPT_ERROR',
      message: `TypeScript compilation errors (${tsErrors.length}+ errors)`,
      details: { tsErrors },
      suggestedFixes: [
        'Fix TypeScript compilation errors in test file',
        'Check import paths are correct',
        'Verify types match expected signatures'
      ]
    });
  }

  // Pattern 5: Jest config issues
  if (stderr.includes('No tests found') || stderr.includes('Cannot find module') && stderr.includes('jest.config')) {
    errors.push({
      type: 'JEST_CONFIG_ERROR',
      message: 'Jest configuration issue',
      suggestedFixes: [
        'Verify jest.config.cjs exists and is valid',
        'Check testMatch patterns include test file location',
        'Ensure roots array includes test directory'
      ]
    });
  }

  // Pattern 6: ESM/Module interop issues
  if (stderr.includes('TS151001') || stderr.includes('esModuleInterop')) {
    errors.push({
      type: 'MODULE_INTEROP_WARNING',
      message: 'ESModule interop warning (usually safe to ignore)',
      suggestedFixes: [
        'Consider adding "esModuleInterop": true to tsconfig.json',
        'This is usually just a warning and won\'t prevent tests from running'
      ]
    });
  }

  // Pattern 7: Test execution timeout
  if (stderr.includes('Exceeded timeout') || stdout.includes('Exceeded timeout')) {
    errors.push({
      type: 'TEST_TIMEOUT',
      message: 'Test execution exceeded timeout',
      suggestedFixes: [
        'Increase Jest timeout in jest.config.cjs',
        'Check for infinite loops in test code',
        'Verify async operations complete properly'
      ]
    });
  }

  return {
    hasErrors: errors.length > 0,
    errors,
    suggestedFixes: errors.flatMap(e => e.suggestedFixes)
  };
}

/**
 * Extract test result summary from Jest output
 */
export function parseJestSummary(stdout: string): {
  passed: number;
  failed: number;
  skipped: number;
  total: number;
} {
  // Look for "Tests: X passed, Y failed, Z skipped, Total total"
  const testsMatch = stdout.match(/Tests:\s+(?:(\d+)\s+passed,?\s*)?(?:(\d+)\s+failed,?\s*)?(?:(\d+)\s+skipped,?\s*)?(?:(\d+)\s+total)?/);

  if (testsMatch) {
    return {
      passed: parseInt(testsMatch[1] || '0'),
      failed: parseInt(testsMatch[2] || '0'),
      skipped: parseInt(testsMatch[3] || '0'),
      total: parseInt(testsMatch[4] || '0')
    };
  }

  // Fallback: no summary found
  return { passed: 0, failed: 0, skipped: 0, total: 0 };
}
